### ISSUE TITLE
Stop logging player stats when there's no need

### ISSUE THREAD

**Issue by cmsu224** [adamk33n3r/runelite-watchdog#1]
![image](https://user-images.githubusercontent.com/14130954/168330181-cd2e3fbe-8795-47eb-b8ee-272f6c626304.png)

**Comment by adamk33n3r** [comment]
Why?

**Comment by adamk33n3r** [comment]
Can you not set the log level higher? I assumed so

**Comment by adamk33n3r** [comment]
I looked more into it and apparently you can't set log level in the client. You *can* pass `--debug` but that's the other direction lol. I'll fix this, my apologies!

**Comment by adamk33n3r** [comment]
Fixed in b21300b509774c8dca21e5dd2dbdf6c8f677b47d
