### ISSUE TITLE
[Feature] Text to speech override.

### ISSUE THREAD

**Issue by MrPryor** [adamk33n3r/runelite-watchdog#104]
Within the settings, you have the option to set your default Elevan Labs voice or the default legacy voice as the override for all new imports, whether they come from the alert hub or are manually added.

Enable a single checkbox to use Elevan Labs if an API key is available; otherwise, the system will default to the legacy voice if you have a default set.

**Comment by adamk33n3r** [comment]
>Within the settings, you have the option to set your default Elevan Labs voice or the default legacy voice as the override for all new imports, whether they come from the alert hub or are manually added.

The default shouldn't be used for imported alerts. It should use the one that is in the imported alert. Does it not? It should only use that default when creating a new one.

>Enable a single checkbox to use Elevan Labs if an API key is available; otherwise, the system will default to the legacy voice if you have a default set.

I suppose we wouldn't even need a checkbox. If you're putting in an API key, we can assume you will always want to use it.

**Comment by MrPryor** [comment]
> The default shouldn't be used for imported alerts. It should use the one that is in the imported alert. Does it not? It should only use that default when creating a new one.
> 

For instance, when I add Wintertodt from the hub, it currently defaults to using voice in the imported alert. It would be a user-friendly enhancement if it could automatically switch to a user's preferred voice by default, eliminating the need to manually edit the voice settings for each individual alert.

**Comment by adamk33n3r** [comment]
Oh ok I understand now. I was thinking something different.

**Comment by MrPryor** [comment]
Similarly, having a default volume for imported would be a welcome addition. 📢

**Comment by adamk33n3r** [comment]
Should we just have a general purpose "override imports" to do everything? The only thing I can think of that might not be great for that would be like colors of things. Like if an imported alert has different colors for different things, it would set them all to the same color.

**Comment by MrPryor** [comment]
Sounds like a good idea! It could be a crucial setting for some users like disabling flashing for users with epilepsy, ects..

**Comment by adamk33n3r** [comment]
Fixed in 1133b491f2ab654e437883524d48d80db6ff3432
