### ISSUE TITLE
Search box breaks after viewing an alert config

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#108]
## Version

2.14.2441-release

## Repro:

1. Type something in the search box at the top of the alerts list which results in the list being filtered.
2. Click one alert to view the config
3. Click back to the list

## What happened:

Now the search box input is cleared, but the alerts list is still filtered.

## What was expected:

The search box input would persist, or the alerts list would restore to the full list.

**Comment by adamk33n3r** [comment]
If I understand this correctly, is the workaround just to type a character in the search box then backspace it?

**Comment by CreativeTechGuy** [comment]
Yup you understand correctly. Not terribly broken, but did give me a little fright thinking that all of my alerts got deleted. 😅

**Comment by adamk33n3r** [comment]
Looks like this is already fixed in v3! I just tested it out. Feel free to reopen if I missed something.
