### ISSUE TITLE
Certain game messages no longer recognised by plugin?

### ISSUE THREAD

**Issue by otygah** [adamk33n3r/runelite-watchdog#109]
Up until recently I was using Watchdog to send a audio notification when my slayer task completed by using the game message 'You have completed your task! You killed' as a watchdog alert. As of a week or two ago it stopped working, while all my other watchdog alerts work fine, eg. Divine potions about to expire messages. Have tried many different excerpts from the Slayer task completion message and no luck.

**Comment by adamk33n3r** [comment]
As of a week or two? Hm, there hasn't been any changes during that time period. Only thing I can think of is if somehow the message changed on RuneScape's side. Do you have wildcards at the beginning and end? Can you export the alert and post it here? Maybe I'll notice something.

**Comment by otygah** [comment]
To be fair, I was taking a break from slayer and doing forestry so could have been longer, I only noticed it not working this past week or two.
Here's the current alert (I changed it to 'return to a slayer master' to try and fix it, but the premise is still the same.

{"type":"ChatAlert","message":"return to a Slayer master.","regexEnabled":false,"enabled":true,"name":"Task","debounceTime":0,"notifications":[{"type":"Sound","path":"C:\\Users\\eddie\\.runelite\\notification.wav","gain":8,"fireWhenFocused":true,"fireWhenAFK":false,"fireWhenAFKForSeconds":1}]}

**Comment by adamk33n3r** [comment]
You definitely need wildcards if you are not matching the ENTIRE message. Try `*return to a Slayer master.*` or `*You have completed your task! You killed*`. I plan on adding wildcards before and after by default in a future release as this seems to confuse a lot of people.

**Comment by otygah** [comment]
This did the trick :) - no idea how I had it working before, then. Thank you!!

**Comment by adamk33n3r** [comment]
Cool, glad that solved it!
