### ISSUE TITLE
[Feature Request] Support for Notification Panel plugin

### ISSUE THREAD

**Issue by iatethedinosaurs** [adamk33n3r/runelite-watchdog#11]
In both the stable release and current 2.0 RC I can't seem to get tray notifications (the ones you can add from the plugin) to appear. I thought maybe it was because I had tray notifications disabled in the RuneLite settings, but even with that option enabled, they don't seem to appear.

I thought that it another possibility could be because I use the Notification Panel plugin, but I've tried disabling that as well. Can't think of anything else that might be interfering with them appearing.

**Comment by iatethedinosaurs** [comment]
Sorry, it just clicked that I disabled them in Windows 10 notification settings, but now I can't get RuneLite to show in the notification settings list to re-enable them.

But the main reason for checking that was that I was going to ask if you would consider adding support for the plugin I mentioned: [Notification Panel](https://github.com/KogasaPls/notification-panel). Having the custom notifications from your plugin show up in the panel that plugin adds would be amazing.

I'm not which developer I would ask to add support for the other's. But I figured I'd try asking here first. Please let me know if I should go ask them.

**Comment by adamk33n3r** [comment]
That's a cool plugin, I'm not sure if I can "support" that plugin but I can look into it if they have a public api. If not, I could potentially create something similar to that as a notification type!

**Comment by adamk33n3r** [comment]
Fixed in 2d5970fd0617de0155e1336f5de12259edf7bfee
