### ISSUE TITLE
Notification doesn't work after duplicating existing alert

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#110]
Version: 3.0.1-release+4144

Repro:

* Create a Game Message alert with a custom sound/flash (not sure if this is relevant or not)
* Clone the alert
* Change the message to a different message that you want it to trigger on
* Now trigger the game message
* The sound/flash will not trigger, but in the alert history, the new alert will show up as having triggered.

The only way I could find to fix it is to turn off Watchdog plugin and back on again. Turning off the problematic alert doesn't fix it.

I'm guessing something in the cloning process breaks it.

**Comment by adamk33n3r** [comment]
Ya, we're not injecting members on clone. Oops.
