### ISSUE TITLE
[Feature] Grouping of Alerts by dragging/dropping

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#116]
I love the Alert Group feature for organizing the alerts into categories and a hierarchy. But I couldn't find a way in the UI to move around the existing alerts and put them into groups so I ended up having to do it all in JSON.

Feature Request:

* Dragging an alert on top of an alert group and dropping will add that alert to the group
* Expanding an alert group and dragging a child alert out of the group will re-parent it up one.

**Comment by adamk33n3r** [comment]
The way I've been doing it is export/import. It's a little inconvenient, but it works. Definitely would be cool to drag/drop and I'd welcome that. But I'm not sure if I have the expertise to implement something like that. I mostly stole the current dragging implementation.

**Comment by CreativeTechGuy** [comment]
It doesn't look like there's a way to import into a group, right?

And maybe an easy option is a right-click "add to group" option similar to the Inventory Setups plugin.

**Comment by adamk33n3r** [comment]
Yes, at the top of the group you can import into one.
