### ISSUE TITLE
Potential Bug: Overhead notification causes gap between health and prayer bar above player

### ISSUE THREAD

**Issue by blubaru14** [adamk33n3r/runelite-watchdog#120]
When I have an overhead notification go off it adds a gap between the hp and prayer bars above the player. This gap remains until I type something in the public chat or log out. And happens again when the first over head notification goes off.

How it looks before an overhead notification:

![image](https://github.com/adamk33n3r/runelite-watchdog/assets/22644953/f991bb99-5675-4cf4-8934-7b93d31df702)

How it looks during an overhead notification:

![image](https://github.com/adamk33n3r/runelite-watchdog/assets/22644953/0e98b73b-9edb-4f55-9205-c5df7800816d)

how it looks after an overhead notification:

![image](https://github.com/adamk33n3r/runelite-watchdog/assets/22644953/da9d58e1-41ae-42ae-862d-b8c175c153e6)

**Comment by adamk33n3r** [comment]
Hm, that is interesting. I know that I'm just calling the `setOverheadText` method so I would think this would be something I don't have control over. After the timer, I then set it to empty string `""` so that may be why it stays that way. Myabe I can set it to `null` instead? It doesn't fix the issue of them being separated, but I think that's just how the game works.

**Comment by blubaru14** [comment]
so using null instead of empty string has the same results? Interesting that typing something in the public chat resets the gap. I'd guess this is also using setOverheadText...but just an assumption.

**Comment by adamk33n3r** [comment]
I don't know if it has the same results, I will have to check. Sometimes passing `null` to functions that don't expect it will throw an exception.

**Comment by blubaru14** [comment]
@adamk33n3r this is another plugin I've use that sets your overhead text. They seem to be doing the overhead text timing a little different though. I do not have the same issues with this plugin toa mistake tracker plugin

https://github.com/QuestingPet/TobMistakeTracker/blob/master/src/main/java/com/tobmistaketracker/TobMistakeTrackerPlugin.java#L221-L224

**Comment by adamk33n3r** [comment]
I just tested it with `null` and it seems to fix the issue. I'm still waiting on my PR from November to be merged, but this fix will be in the next one.

**Comment by adamk33n3r** [comment]
oh interesting, i didn't know about `setOverheadCycle`. Maybe that will be the solution
