### ISSUE TITLE
[Bug] XP Drop alerts are fired immediately upon logging in

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#121]
When you log in, any XP Drop events are immediately triggered since logging in will send the client a bunch of "XP gained" messages. It'd be great if the plugin ignored these initial XP notifications during the login process.

**Comment by adamk33n3r** [comment]
Struggling to find a good solution to this. Unfortunately these events are fired after the `LOGGED_IN` game state so I can't differentiate between logging in or playing as it's the same state. I had a thought to keep track of "the first time we get the xp drop" that I'll try out.

**Comment by adamk33n3r** [comment]
Looks like this would only happen on your first login. The game client would report 0 XP for your skill upon first login, but would be accurate on subsequent logins as long as RuneLite wasn't closed. But I think I figured out a fix for it regardless!
