### ISSUE TITLE
[Feature] Inventory Change

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#124]
It'd be super powerful if the Inventory alerts could alert when something changed (eg: an item was added, removed). I see this as a setting under the current Inventory type=item alert, which when active, would change "quantity" to be the delta change. I suspect that it would only allow `-1` or `1` since it's super rare for multiple items to be added/removed in the same tick.

This would require keeping track of the current inventory each tick, and then comparing it to the next tick. We wouldn't need any history beyond one tick history so it should be pretty simple™.

I'm happy to contribute if accepted.

-----

An example use-case that this would enable. With the new Overlay/Dismiss Overlay feature, we could have an overlay appear when a Bracelet of Slaughter breaks, and then dismiss the overlay when the number of bracelets in your inventory decreases by one. (Same would apply to most consumable jewelry.)

**Comment by adamk33n3r** [comment]
Oh ya that could be cool, the inventory alert I think needed an improvement....but I can't remember what it was. Maybe it was stack vs item slot? There's also #69 but that's a little more complicated.

**Comment by CreativeTechGuy** [comment]
How do you want to tackle this? Should it be more features added to the existing alert somehow, or separate alerts?

**Comment by adamk33n3r** [comment]
I think it would make sense as and option to the existing alert, ya?

**Comment by CreativeTechGuy** [comment]
Yeah seems fair. Do you have a design for it and/or want to implement it yourself or should I just wing it?

**Comment by adamk33n3r** [comment]
If you want to tackle it, go for it! :)

**Comment by CreativeTechGuy** [comment]
I finally got around to this. Sorry for the delay. It was actually really easy with the code you already had. Thanks! :)

**Comment by adamk33n3r** [comment]
No worries! I'll review it tonight.
