### ISSUE TITLE
Color picker for overhead

### ISSUE THREAD

**Issue by August1nFR** [adamk33n3r/runelite-watchdog#128]
Similar to how you can do 'red: hello' in game to type a red 'hello' message. Would it be possible to color the overhead text? Funny enough if i type a message and give it a color in game and then trigger and overhead with the plugin, that text will be of the same color as the message i send in game until i type something new. Thanks !

**Comment by adamk33n3r** [comment]
That's interesting that it works like you describe.....lol. But you can do this by surrounding your text in a col tag `<col=3366cc>TEXT HERE</col>`

**Comment by August1nFR** [comment]
Oh wow thanks for the help, i guess i was also thinking it would be cool if there was some kind of color picker implemented to make it easy for ppl like me. Will definitely use the method you posted though. Thanks :p

**Comment by adamk33n3r** [comment]
Ya, it's definitely an undocumented feature and kind of getting into the internals of runelite. We could probably add a color picker pretty easily to expose that. Unfortunately might be a bit as I just submitted the next release the other day.
