### ISSUE TITLE
[Feature] Simplified Alert Moving

### ISSUE THREAD

**Issue by Brandarf** [adamk33n3r/runelite-watchdog#134]
**Describe the solution you'd like**
Currently, to move alert(s) or alert group(s) to another group, you have to export the JSON, and import it into the group you want it in (other than making a new nested group). Is there a way you could use select mode to move selected alerts "up one group" (not sure how to word this properly), or to move them to another group elsewhere? 

Example:

Varlamore Group
-Citizen Distracted ALERT
-Coin Bags Full ALERT
-Random Request ALERT

Requests Group
-First Request ALERT

Let's say I accidentally made the Random Request Alert in the Varlamore Group, but I wanted it in the Requests Group. Currently I have to export the JSON, copy it, paste it in the requests group, and delete the original. Not that its difficult or anything, but it would be nice to have a "move selected alerts / groups up one level" and to be able to move it from one place to another in a little simpler manner. Hope that makes sense :)

**Comment by adamk33n3r** [comment]
Ya I'm planning on adding a move up option 👍

**Comment by Brandarf** [comment]
Awesome! Will you be able to move selected alerts/groups from current level into an already existing alert group? Or still have to create a new one? Thanks 🥇

**Comment by adamk33n3r** [comment]
I'm not sure how the UI would work for that, I can only think of complex gross methods lol. So probably not.
