### ISSUE TITLE
[Bug]When using the Item Change notification type, it doesn't check for X->0

### ISSUE THREAD

**Issue by Brandarf** [adamk33n3r/runelite-watchdog#136]
**Describe the bug**
When using the Item Change notification type, it doesn't check for X->0, so when you are using the last item in a stack, or last of an item you have multiple of in your inventory of, it won't fire. 

**To Reproduce**

1. Create an alert using the inventory->item change notification type
2. Set an item name, and set it to check "== -1"
3. While you have more than 1 of the item, it will fire, when you get to the last item, it won't.

**Expected behavior**
It to continue to fire for the last inventory item used.

**Screenshots**
![image](https://github.com/adamk33n3r/runelite-watchdog/assets/166973821/bfc0cb16-11a3-4fda-ad11-67a6367e21a4)

**Additional context**
Making a Kraken alert group.

**Comment by adamk33n3r** [comment]
Fixed by #145
