### ISSUE TITLE
[Feature] Clearing notifications upon interaction w/ client/particular action is taken

### ISSUE THREAD

**Issue by G-lint** [adamk33n3r/runelite-watchdog#139]
Firstly forgive me if I'm submitting this in the wrong place. I don't commonly use GitHub so I'm a bit lost when it comes to submitting things like this.

Unless I'm missing something at the moment, watchdog notifications are all time based, meaning they will all play for a predetermined amount of time. I would love to be able to pick a certain actions/interactions that would clear notifications instead.
To give an example:

> I am running blast furnace and my stamina dose expires. Watchdog alert activates notifying me by playing a sound and adding a screen marker over where the potions is located in my bank. Once I remove the dose and take a sip (I would ideally trigger on this sip) the watchdog notification is cleared only to be reactivated once my stamina dose is low again.

I would also find use out of this with overlays. I enjoy having the overlay on screen letting me know what actions need to be taken, and once they have been, it would be nice for them to automatically be removed from my screen.

> Example of this would be being in NMZ and your overload is expiring. Notification is triggered adding "Overload" overlay next to inventory. Once you take a sip of your overload, this notification clears!
![image](https://github.com/adamk33n3r/runelite-watchdog/assets/89947471/595e54ee-1955-4357-a2b6-5cd1e306f9e6)

Possible solutions to the ones above, sipping a potion makes a sound (Sound ID: 2,401), when this sound is played clear the notifications. This might run into issues of game sounds are muted.
There is also chat messages the appear each time a potion is consumed, and with the eye dropper, that could also be a solution!
I'm sure there are other clever answers I'm not thinking of at the moment but this is at least a starting point! 

Hopefully that all makes sense. This is by far my favorite plugin on the whole hub and I'm only more and more excited to see how it evolves!

**Comment by Brandarf** [comment]
Have you looked into how sticky overlays work? You can dismiss a sticky overlay by ID.

**Comment by G-lint** [comment]
I noticed it for Overlays but when entering the sounds ID nothing seems to happen (currently just have the number enter into the field, tried both with and w/o the comma). This is almost 100% user error, I'm just unaware of how to enter the ID to get it to work as like I listed above.

I would still be nice to have it work with other notifications also like the screen markers!

**Comment by adamk33n3r** [comment]
> I noticed it for Overlays but when entering the sounds ID nothing seems to happen (currently just have the number enter into the field, tried both with and w/o the comma). This is almost 100% user error, I'm just unaware of how to enter the ID to get it to work as like I listed above.

It has nothing to do with sound id's. You give your overlay an ID and then you use that ID in a Dismiss Overlay notification to close it.

**Comment by adamk33n3r** [comment]
@G-lint did you figure out how to use the dismiss overlay notification?

**Comment by adamk33n3r** [comment]
Closing as stale
