### ISSUE TITLE
[Bug] Import (Append) erases all alerts and doesn't add alert being imported.

### ISSUE THREAD

**Issue by iatethedinosaurs** [adamk33n3r/runelite-watchdog#14]
Hello, loving the new update! I've been having a blast customizing my alerts using regex. I really appreciate your work!

I've run into a problem while trying to import alerts. Clicking the Import (Append) button erases the entire notification list and doesn't actually add the notification it was supposed to. 

I thought it might just be a visual bug, but restarting the Runelite client, the notification list is indeed empty. 
I also thought that it might be just a certain notification types being imported that could be causing it, but it's consistent across all notification types

Steps to reproduce:
1. Click Import on main panel
2. Paste any exported notification ex: `[{"type":"NotificationFiredAlert","message":"Crystal impling is in the area","regexEnabled":false,"enabled":true,"name":"Crystal Impling","debounceTime":0,"notifications":[{"type":"ScreenFlash","color":"#46FF0000","flashNotification":"SOLID_TWO_SECONDS","fireWhenFocused":false}]}]`
3. Click Import (Append)

It may be worth mentioning that Import (Overwrite) is working properly.

**Comment by adamk33n3r** [comment]
Hey thanks for reporting this and for the kind words! I must have missed something when I redid the way notifications are saved automatically. I'll hopefully be able look into this today.

**Comment by adamk33n3r** [comment]
This has been PR'd to the plugin hub https://github.com/runelite/plugin-hub/pull/3769 and I've asked for it to be looked at urgently since it can wipe data without question so hopefully it'll be merged in soon :)
