### ISSUE TITLE
[Bug] Inventory Change Doesn't Detect Decrease to Zero

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#144]
**Describe the bug**

If you setup an Inventory Alert with type Item Change with a quantity of `-1`, it won't trigger if the remaining items left in your inventory are now zero.

**Expected behavior**
It triggers even if there are no matching items left.

**Code link**

* [The building of the allItems list - only from what is currently in your inventory](https://github.com/adamk33n3r/runelite-watchdog/blob/f98756856929e0505c27c2fa7022526f9b6c67e9/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L212-L214)
* [The looping through your inventory to find which alerts to fire](https://github.com/adamk33n3r/runelite-watchdog/blob/f98756856929e0505c27c2fa7022526f9b6c67e9/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L231-L242)

I think there's two potential solutions:
* Do the same loop with `allItems` and also `this.previousItemsTable` so you can check both.
* Copy the `allItems` map to a new one (as to not mess up [this line](https://github.com/adamk33n3r/runelite-watchdog/blob/f98756856929e0505c27c2fa7022526f9b6c67e9/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L246)), then add any items found from `this.previousItemsTable` to the new map with zero quantity so they don't get missed.

**Additional context**

Sorry I'm pretty sure that was my code that's broken here. 😬

**Comment by CreativeTechGuy** [comment]
Oops I realized this is a duplicate of #136. I missed that one.

**Comment by adamk33n3r** [comment]
Oh ya, I had THOUGHT it was already tracked but I missed it too when I looked :P
