### ISSUE TITLE
[Feature] Increase Overlay timeout limit

### ISSUE THREAD

**Issue by Megaddd** [adamk33n3r/runelite-watchdog#154]
**Describe the enhancement**
Overlay timeout is limited to ~1.5min tops, even though there are many events you would like timed for up to a few minutes at least.

**Comment by adamk33n3r** [comment]
At that point, you can use Sticky, no? Can you give me an example of the many events you would need more than 99 seconds?

I'm not sure what you mean by the term "timed", this isn't for timing things, it's just how long you'd like the notification to fall off. If you'd like to time something, use the delay option on a notification. That can go up to 5 minutes.

**Comment by adamk33n3r** [comment]
Oh so you'd like it to be running the whole time the event is active? I can see that. Thanks for the explanation.
