### ISSUE TITLE
Please add compatibility for the new npc_say Chattype

### ISSUE THREAD

**Issue by wizzyhatg** [adamk33n3r/runelite-watchdog#158]
**Describe the solution you'd like**
Add support for the npc_say chattype added to runelite I believe here? https://github.com/runelite/runelite/commit/eab40b3e27a25a43cd5233fccc56fee048de5adb Which is used by Nex and possibly other stuff?

**Describe alternatives you've considered**
_I will try to fix this myself but am very not confident_ Was not able to identify a fix myself

**Additional context**
Nex Nostalgia implemented similar functionality with this https://github.com/hex-agon/runelite-plugins/commit/c81095b0b357b380e7894ee5baf4611044456884

**Comment by wizzyhatg** [comment]
{"type":"AlertGroup","alerts":[{"type":"ChatAlert","message":"*Glacies, don\u0027t*","regexEnabled":false,"gameMessageType":"ANY","enabled":true,"name":"Glacies","debounceTime":0,"randomNotifications":false,"notifications":[{"type":"Overlay","color":"#4600FFDD","textColor":"#FFFFFFFF","sticky":false,"timeToLive":5,"imagePath":"","message":"Glacies","fireWhenFocused":false,"fireWhenAFK":true,"fireWhenAFKForSeconds":5,"delayMilliseconds":0}]},{"type":"ChatAlert","message":"Nex: Cruor, don\u0027t fail me*","regexEnabled":false,"gameMessageType":"ANY","enabled":true,"name":"Cruor","debounceTime":0,"randomNotifications":false,"notifications":[{"type":"Overlay","color":"#4600FFDD","textColor":"#FFFFFFFF","sticky":false,"timeToLive":5,"imagePath":"","message":"Cruor","fireWhenFocused":true,"fireWhenAFK":false,"fireWhenAFKForSeconds":5,"delayMilliseconds":0}]},{"type":"ChatAlert","message":"Nex: Umbra, don\u0027t fail me!","regexEnabled":false,"gameMessageType":"ANY","enabled":true,"name":"Umbra","debounceTime":0,"randomNotifications":false,"notifications":[{"type":"Overlay","color":"#4600FFDD","textColor":"#FFFFFFFF","sticky":false,"timeToLive":5,"imagePath":"","message":"Umbra","fireWhenFocused":true,"fireWhenAFK":false,"fireWhenAFKForSeconds":5,"delayMilliseconds":0}]},{"type":"ChatAlert","message":"Nex: Fumus, don\u0027t fail me!","regexEnabled":false,"gameMessageType":"ANY","enabled":true,"name":"Fumus","debounceTime":0,"randomNotifications":false,"notifications":[{"type":"Overlay","color":"#4600FFDD","textColor":"#FFFFFFFF","sticky":false,"timeToLive":5,"imagePath":"","message":"Fumus","fireWhenFocused":true,"fireWhenAFK":false,"fireWhenAFKForSeconds":5,"delayMilliseconds":0}]}],"enabled":true,"name":"Nex","debounceTime":0,"randomNotifications":false}

This used to work, now it doesn't. My understanding is that this isn't due to any Jagex compliance policy change or whatnot but just due to a runelite change where this plugin doesn't capture Nex's chat dialogue under "gameMessageType":"ANY" anymore. Looks like Nex Nostalgia fixed it by adding npc_say

**Comment by adamk33n3r** [comment]
Should be able to add a new type here https://github.com/adamk33n3r/runelite-watchdog/blob/f211a0035af87517c32b9381bc2e3fc54d16d664/src/main/java/com/adamk33n3r/runelite/watchdog/GameMessageType.java#L12
