### ISSUE TITLE
[Feature] Option for regexes to use the sum of all items that match

### ISSUE THREAD

**Issue by daltonpearson** [adamk33n3r/runelite-watchdog#161]
**Describe the solution you'd like**
An option to make inventory alerts use the sum of all items that match a regex rather than the current behavior of each unique item needing to reach the given threshold

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/user-attachments/assets/bd207230-b158-4dae-b1ab-4825b20ab3ac)

**Comment by adamk33n3r** [comment]
Dev note: I think our inventory map is just using the name of the item for count, it can perhaps be using the pattern input instead
