### ISSUE TITLE
Add option to change Side Panel Position 

### ISSUE THREAD

**Issue by krymk** [adamk33n3r/runelite-watchdog#167]
I would like an option to choose the side panel position in the configuration of the watchdog plugin. It would be a number input box, 0 would put the side panel icon on top of all other icons, every number after would put the icon under the next icon.

This feature already is in the 'Bossing Info' plugin.
Example: https://imgur.com/a/LN2KmQc

**Comment by adamk33n3r** [comment]
I could probably do something like that. I've been wanting that to be in core for so long. Wouldn't it be nice to just be able to drag them around?

**Comment by adamk33n3r** [comment]
Looks like it's being theoretically being worked on here https://github.com/runelite/runelite/pull/18406
