### ISSUE TITLE
Notification when focused

### ISSUE THREAD

**Issue by pettrs** [adamk33n3r/runelite-watchdog#18]
It appears notifications will not trigger if the client is focused, or at least TTS. This appears to be true regardless of enabling "send notifications when focused" enabled in #runelite. it also seems to only be affecting this notification plugin, not others like chat notifications, idle notifications, etc...

Current settings are
![image](https://user-images.githubusercontent.com/75093127/213025734-c8fd3133-17e5-467d-8847-c17277a4d881.png)
![image](https://user-images.githubusercontent.com/75093127/213025976-3d5bc37e-092e-4b14-b6f0-b7845756455f.png)

**Comment by adamk33n3r** [comment]
The RuneLite settings have nothing to do with this plugin. You can think of this plugin as a replacement for the "Notification Settings" in RuneLite.

That being said, there is an "in focus" toggle on each notification. Turn that on and it should work.
![image](https://user-images.githubusercontent.com/1350444/213028118-e7813bc4-4ba9-4f38-9a01-bb68a1e3927e.png)

**Comment by adamk33n3r** [comment]
Did this resolve your issue?

**Comment by pettrs** [comment]
Yes!
