### ISSUE TITLE
[Bug] Notification Fired Alert doesn't seem to be autosaving last edits.

### ISSUE THREAD

**Issue by iatethedinosaurs** [adamk33n3r/runelite-watchdog#22]
I noticed this earlier today when I restarted my client. I had an Ancient shard drop and my custom notification sound didn't go off. The changes I made to my Notification Fired Alert didn't seem to save when I restarted my RuneLite. I am able to reproduce the bug doing the following:

1. Launch RuneLite
2. Import (Append) `[{"type":"NotificationFiredAlert","message":".*Untradeable drop:.*(\\bCrystal shard|\\bAncient shard|\\bLong bone|\\bCurved bone|\\b)","regexEnabled":true,"enabled":true,"name":"Untradeable Drop","debounceTime":0,"notifications":[{"type":"ScreenFlash","color":"#4687FF00","flashNotification":"FLASH_TWO_SECONDS","fireWhenFocused":true}]}]`
3. Edit the trigger message (ex. remove the last |\b)
4. Return the plugin main panel (attempting to force changes to be saved)
5. Exit RuneLite

Upon restarting RuneLite the trigger message will still have the `|\b` that was removed. 
In my case, I also had a custom sound play and the volume wasn't being saved either. 
This is reproduce-able on both my clients.

Forgot to note that it does not seem to be affecting other notification types from my brief testing.

**Comment by adamk33n3r** [comment]
Thank you for reporting this! v2 brought with it auto-save and that meant I had to add change listeners to every control. It appears that I have missed some!

**Comment by adamk33n3r** [comment]
I've pushed up a fix, and I also made it save when clicking Back just in the small case that I miss anything else.
