### ISSUE TITLE
[Feature] Additional settings for Overlay notification

### ISSUE THREAD

**Issue by iatethedinosaurs** [adamk33n3r/runelite-watchdog#23]
Hello, I've been playing around with the new release some using the shadow jar and I love the implementation of the Overlay notification type. It will pretty much replace the Notification Panel plugin for me in due time. I did have some requests for additional settings in the plugin settings for the notification type.

- Default alignment: currently it is left-aligned which makes it look funky when the notifications aren't the same size. Could you allow this to be set to centered? Or maybe centered as default to make it look cleaner under default settings.
- Font style: (Currently set as bold) Can we adjust this to Small or Regular?
- Default color setting: (Currently set to red) Allowing a custom default color would be neat.
- Time: Could there be an option to hide the time since the notification fired? It would make things a bit cleaner.

Thank you! I really appreciate your work!

**Comment by adamk33n3r** [comment]
Awesome, thanks for checking it out! And ya I did want to have it center aligned, but it seemed a little complicated to get that working. A lot of manual stuff. I'll definitely work on that, figured this would be a good intermediate for now.

Default color: it's currently set to the same default color as screen flash. The color picker has a recent color section so it should be easy to have your favorites. I'm not necessarily against the idea, but having defaults for just the notification panel and not other notification types. So I think if want to support all types or none. 

Font 👍
Time 👍

**Comment by iatethedinosaurs** [comment]
Ah I see, no worries. It is at a good place for now. But thank you for looking into making it center aligned.

I understand that, so it is probably best to leave as is. I must have overlooked the recent color section, sorry. But with that knowledge this suggestion can be disregarded, since that is exactly what I was looking for.

Awesome, thank you!

**Comment by adamk33n3r** [comment]
do you think the font or time settings should be per notification or a global setting? I'm leaning toward global.

**Comment by adamk33n3r** [comment]
Now that I have had a little more time to think about it, the reason I didn't center the text was because it was "easy" to do using `TitleComponent`, but there wasn't any wrapping functionality. `LineComponent` has wrapping functionality but doesn't support centering. So, I figured since I'd have to make my own custom solution to support both, I'd just use `LineComponent` since I thought wrapping was more important.

**Comment by adamk33n3r** [comment]
![image](https://user-images.githubusercontent.com/1350444/214724821-87cd637b-691d-47fb-b8e9-67cd6f85fc11.png)
Ok well that wasn't too bad. Basically just merged RuneLite's `TitleComponent` and `LineComponent` :P

**Comment by iatethedinosaurs** [comment]
I can't even begin to tell you how excited I am to test this out. Thank you for putting it out so quickly! I might make it my main driver running the shadow jar through a bat file while RuneLite gets it updated on the plugin hub. I just need to figure out how to get the client args for both accounts working through said bat. Thanks again!
