### ISSUE TITLE
Plugin Not Working?

### ISSUE THREAD

**Issue by Popedigoz** [adamk33n3r/runelite-watchdog#25]
Hey,

I wanted to make two simple alerts; low HP & low prayer with TTS. From the plugin settings (gear icon) I did tick the "Enable TTS" and allowed the 3rd party to use my IP in the pop-up.

I can't make this plugin work at all, I get no notifications/alarms at all. Should I toggle idle notifier off or smth?

What determines _how low_ **is** _low_ HP/prayer? There's no way to type in the values?

What does "Notification Fired Alert" mean? The only hint is "The message to trigger on. Supports glob (*)" <- and the hint message cuts off. what's glob?

If I want to make new low prayer alert, I:

1) Press the + sign (Create New Alert)
2) Select Stat Drain?

I mean... there is no way to get the same kind of alert as the pre-existing 'Low HP' example (there is option for the "Resource" in new ones), which isn't even working for me.

**Comment by adamk33n3r** [comment]
>What determines how low is low HP/prayer? There's no way to type in the values?
You do type in the values. 

![image](https://user-images.githubusercontent.com/1350444/214915672-f9b926af-e387-4548-bb5f-3df9cd4c6f01.png)
>What does "Notification Fired Alert" mean? The only hint is "The message to trigger on. Supports glob (*)" <- and the hint message cuts off. what's glob?

Notification Fired Alert is an alert that triggers on when a RuneLite Notification Fires. The README explains it pretty well, "allows you to hook into existing notifications, even if you have the alerts off in Runelite. For example low prayer, idle, tempoross, etc". I don't see any hint "cutting off". You can google glob, but as a simple example you can use `*` to mean "any text". So, you could do `*is ready to harvest*` to trigger on any of your crops being ready.

>there is no way to get the same kind of alert as the pre-existing 'Low HP' example (there is option for the "Resource" in new ones), which isn't even working for me.

If you're referring to the old examples, those didn't have any notifications added on them. There are new examples now but you won't get them unless you clear your alerts. I'm not sure what you mean by "Resource".

Here's an example low prayer alert using Stat Drain
![image](https://user-images.githubusercontent.com/1350444/214917984-f62ac19e-d87a-4c58-be4a-5276ea162180.png)
and an example using Notification Fired which hooks into the notification sent by the Idle Notifier plugin
![image](https://user-images.githubusercontent.com/1350444/214919285-5585891d-97ec-4172-bed4-9693a0333c8f.png)

Let me know and reopen this issue if there is something actually broken, but I think it this is just user error.

**Comment by Popedigoz** [comment]
> > What determines how low is low HP/prayer? There's no way to type in the values?
> > You do type in the values.

**I see it now (since I'm not using the old example/presets anymore).**

> 

> > there is no way to get the same kind of alert as the pre-existing 'Low HP' example (there is option for the "Resource" in new ones), which isn't even working for me.
> 
> If you're referring to the old examples, those didn't have any notifications added on them. There are new examples now but you won't get them unless you clear your alerts. I'm not sure what you mean by "Resource".

**The "Resource" was a list for HP, prayer and some others in the old pre-existing example of Low HP preset, I've cleared everything now to get the new ones.**

> Here's an example low prayer alert using Stat Drain and an example using Notification Fired which hooks into the notification sent by the Idle Notifier plugin
> 

Tried your example about low prayer alert, not working.

@adamk33n3r Hey, here is a video of me demonstrating it not working, I copied your example's settings:
https://www.dropbox.com/s/8ypjw9plkqqr3c7/healthISlow.mp4?dl=0

Should it matter whether or not your client is focused or not?

**Comment by Popedigoz** [comment]
> Hopefully that does it for you.

**That was it.**


> I've wondered if I should make in-focus be the default.

**Definetly yes. I thought I had that already enabled because, I did in fact, actually press the button - however that was on the old example, and I didn't realize the setting was per alert.**

**Comment by adamk33n3r** [comment]
> and I didn't realize the setting was per alert
It's per notification, even!
