### ISSUE TITLE
[Feature] Add TTS Brian Male UK

### ISSUE THREAD

**Issue by Popedigoz** [adamk33n3r/runelite-watchdog#27]
This one: https://readloud.net/english/british/1-male-voice-brian.html

**Comment by adamk33n3r** [comment]
I do not control the TTS service so unfortunately I'm not able to add anything. I am using Bullish's service from the TTS plugin https://runelite.net/plugin-hub/show/tts

I would like to eventually switch to something I control, but it would be a lot of work that I'm not prepared to tackle yet. I'll keep this in mind though!

**Comment by adamk33n3r** [comment]
I'm going to close this as we now have eleven labs tts. Not exactly the same, but I think we'll probably keep what we have for now.
