### ISSUE TITLE
[Feature] Screen flash - Solid until canceled no mouse movement 

### ISSUE THREAD

**Issue by Popedigoz** [adamk33n3r/runelite-watchdog#28]
About **_Screen flash_ - _Solid until cancelled_**...

It seems that cursor movement triggers "cancellation". I would like it _not_ to. Could it be changed to LMB, RMB, Mouse3 or any key press? My RuneLite's setting for always focused.

**Comment by adamk33n3r** [comment]
The screen flash is a copy of the default Runelite screen flash so it works exactly the same. I could potentially add that as an option, but for right now it behaves the same for consistency.
