### ISSUE TITLE
[Feature] Capture groups for Overlay notification

### ISSUE THREAD

**Issue by iatethedinosaurs** [adamk33n3r/runelite-watchdog#29]
I've been playing with the latest update and it's looking amazing! I wanted to ask if you could add the capture groups feature to the Overlay notification. Thanks to your tests on the capture groups commit, I figured out how to get it working with regex enabled. (might I suggest adding that to the plugin description: {\*} when regex is disabled, (.\*) when regex is enabled, or similar.)

I did have another question, not regarding the plugin. But it's preferred to make separate issues for each feature request, right? Rather than make a single issue with multiple requests? Just feeling like I might be making too many and wanted to make sure.

**Comment by adamk33n3r** [comment]
> I've been playing with the latest update and it's looking amazing! I wanted to ask if you could add the capture groups feature to the Overlay notification. Thanks to your tests on the capture groups commit, I figured out how to get it working with regex enabled. (might I suggest adding that to the plugin description: {\*} when regex is disabled, (.\*) when regex is enabled, or similar.)

This was definitely an oversight. I'll definitely do that! Also, that's a fair point about capture groups. I was assuming people knew that parentheses are used for regex (and curly braces are something else in regex). But I should probably specify just to be clearer.

> I did have another question, not regarding the plugin. But it's preferred to make separate issues for each feature request, right? Rather than make a single issue with multiple requests? Just feeling like I might be making too many and wanted to make sure.

Yes, multiple issues would be best! Just easier to track stuff!
