### ISSUE TITLE
Watchdog doesn't seem to work for partial game messages

### ISSUE THREAD

**Issue by Marstead** [adamk33n3r/runelite-watchdog#4]
Hey there, I may be doing something wrong here, but it seems like Watchdog will not fire a TTS notification when a partial chat message is received.

I have the plugin enabled to send a game message when a Random Event spawns for example, and Chat Notifications is set to "Random event spawned", but the plugin will only fire a TTS notification if the entire message is entered like "Random event spawned: Bee keeper".

Being able to enter partial messages and get them to fire is a big part of the value of notifications for me, so that I can get complex notifications like "Ready to harvest" (any) or "Random event spawn (any)" or "XP Left to Level (Some Number)" to all trigger an individual notification.

Can this plugin be updated to support partial messages, maybe as a checkbox option? Thank you!

**Comment by adamk33n3r** [comment]
Chat alerts support glob patterns, so you should be able to get your desired effect by using `Random event spawned*`. I thought for sure I had that displayed somewhere but looking at the code maybe not. So I'm sorry for that! I'll update the Readme at least.

**Comment by Marstead** [comment]
> 

Thank you! Just to be clear, sometimes I need an alert fired based on text in the middle of a message, does that just involve putting * before and after the message?

**Comment by adamk33n3r** [comment]
That is correct! Let me know if that works for you! :)

**Comment by Marstead** [comment]
****

> That is correct! Let me know if that works for you! :)

That fixed it, thank you!
