### ISSUE TITLE
increase debouncetimer

### ISSUE THREAD

**Issue by pettrs** [adamk33n3r/runelite-watchdog#40]
Currently, it's limited to 60 seconds, can this be increased to 10-20 mins?

**Comment by adamk33n3r** [comment]
You mean so that an alert will only fire once every 10-20 minutes? What is your use case?

**Comment by pettrs** [comment]
It would be for guardians of the rift. I want a notification for the first portal spawn, but not the 10 next ones. so if i put that timer to 10 minutes, it will have cooled down by the time the game restarts

**Comment by adamk33n3r** [comment]
I could see issues arising if you get out of sync with whatever you're trying to track, and no way to "reset" it unless you just wait an indeterminate amount of time.

I'm not entirely against increasing the timer, but its formatted in milliseconds so for 10 minutes that would be 600,000. That's a huge number to support in the UI. I'll look into it though.
