### ISSUE TITLE
Animation ID trigger

### ISSUE THREAD

**Issue by Cisney-Gassai** [adamk33n3r/runelite-watchdog#41]
Currently the plugin let you set a notification based on sound IDs, could it be possible to set them too based on animation IDs? or even model IDs too.

**Comment by adamk33n3r** [comment]
I don't think we're going to implement this. It opens up too big a can of worms with regards to the Jagex 3rd party guidelines https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

**Comment by Cisney-Gassai** [comment]
Sure I understand, and what about a sound ID tester? Just a button so you can hear again the sound ID you input.

**Comment by adamk33n3r** [comment]
That is a decent idea, but actually in the next release there will be a Sound Effect notification that you could use to test out the sound effects.
![image](https://user-images.githubusercontent.com/1350444/221492939-fa5cdc23-e5f1-4b7a-9a2f-d4bf4821cc13.png)

**Comment by Cisney-Gassai** [comment]
Amazing! Thank you, that helps a lot.
