### ISSUE TITLE
[Feature] New trigger for various inventory states

### ISSUE THREAD

**Issue by SpySeaBoi** [adamk33n3r/runelite-watchdog#52]
Have a trigger for states in your inventory to help with afk skilling. Examples include:

-Empty inventory (POH altar runs)
-Full inventory (fishing/mining runs)
-a certain amount of a specific item (having 14 maple longbows for fletch stringing)
-a stack reaching a certain amount (max stack coin pouch for AFK knight of ard. thieving training)

**Comment by adamk33n3r** [comment]
This has been released in https://github.com/adamk33n3r/runelite-watchdog/releases/tag/v2.10.0-rc2. Still working on some quirks, so feedback would be appreciated!
