### ISSUE TITLE
[Feature] Duration of sound settings

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#54]
Similar to the Screen Flash duration (where you can set it to 0 to flash until cancelled, or a number of seconds to flash), it'd be great if the sound could have those same options. So either keep repeating the sound file until cancelled (same as the flash cancellation) or repeat the sound until a certain time has elapsed. (Not sure if it should cut off the sound immediately at time or let the sound complete and just stop repeating. I guess whichever is easier since the sounds should be super short anyway.)

**Comment by CreativeTechGuy** [comment]
@adamk33n3r Something I thought of that needs to be implemented as part of this is a way to shut off all repeating sounds. I'm thinking at the very least, when the player is logged out or hops worlds, it should cancel all repeating sounds, regardless of the settings. That way if someone accidentally sets a sound to repeat for an hour or is AFK and the sound is repeating when the player isn't at the computer anymore, it'll stop eventually.

**Comment by adamk33n3r** [comment]
ya that's a good point

**Comment by adamk33n3r** [comment]
could probably do it on any game state change

**Comment by adamk33n3r** [comment]
Re-opening since there is more to do here

**Comment by CreativeTechGuy** [comment]
What is remaining to do here?

**Comment by adamk33n3r** [comment]
> What is remaining to do here?

Um, I think it was what I did here https://github.com/adamk33n3r/runelite-watchdog/commit/b87e629b998c3645d8f2d344e2209a6745937698 so we can probably close this.
