### ISSUE TITLE
[Community] Location to share/collaborate on alerts

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#55]
Possibly enabling the Discussion tab of the repo could be a good place for users to share what they've made. I'm sure a lot of power users have made dozens of really fancy alerts which others may want to import or use as a reference or ideas. There are a lot of advanced use-cases for this plugin and it only is becoming more powerful with every update, so a place for the community to discuss with each other and share things would be awesome!

**Comment by adamk33n3r** [comment]
I wholeheartedly agree, and we have the discord server for exact purpose! Unless you think we should additionally have something up here, I think that should be enough. Most people don't have github accounts anyway, I've seen that be a pain point.

**Comment by CreativeTechGuy** [comment]
Ah good point. I would never have considered Discord for this sort of thing. Ignore me. Glad you already got this solved. Great job! :)

**Comment by adamk33n3r** [comment]
No problem! You can check out the #alert-share channel there! :D
