### ISSUE TITLE
[Bug/Feature] Bad RegEx doesn't tell the user the error

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#56]
I noticed when working on my own RuneLite plugin and running RuneLite with debug mode on that one of my regex patterns for this plugin was causing a parsing error. I had improperly escaped something so had an unclosed capture group. It was super easy to fix since I saw the error message, but that was only in the debug console of RuneLite which most players would never see.

Can these errors be surfaced to the player somehow so they know what the problem is? Maybe a chat notification or an alert box?

**Comment by adamk33n3r** [comment]
That's a good point. It probably would only error if you're getting a chat message etc so it would probably be bad/spammy to show an error every time. Maybe I can separately "validate" the regex on unfocus of the input by just running the regex with some dummy text.

**Comment by CreativeTechGuy** [comment]
In my experience (sample size of 1) I saw the error on load (when RuneLite first started). It looks like [the regex is recompiled on every message](https://github.com/adamk33n3r/runelite-watchdog/blob/bf4ee4a8735e609a9d64d670cc3d02754ed8891b/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L102), maybe if it was compiled and cached when the configuration changed then at that point the error can be shown?

**Comment by adamk33n3r** [comment]
That's weird that it would be compiled on load....like you say, it's only compiled on chat messages. Oh and I guess [on notifications](https://github.com/adamk33n3r/runelite-watchdog/blob/bf4ee4a8735e609a9d64d670cc3d02754ed8891b/src/main/java/com/adamk33n3r/runelite/watchdog/EventHandler.java#L127). Maybe there are notifications on startup.

**Comment by CreativeTechGuy** [comment]
I'm sorry I didn't reproduce it. :( It may have been right after login. I don't recall. But luckily I think the solution is the same either way.

Anyway, appreciate your work on this plugin. Much appreciated like always!

**Comment by adamk33n3r** [comment]
Here's an example!
![image](https://user-images.githubusercontent.com/1350444/232258163-5af28188-4dff-4af2-856d-0e88fefdb481.png)

**Comment by CreativeTechGuy** [comment]
Amazing! Does this show when you import a JSON config too?

**Comment by adamk33n3r** [comment]
Hmmm, no it wouldn't. This is only triggered when the input text box loses focus. Theoretically this shouldn't happen on importing json since you wouldn't be able to export invalid regex. Do you think it would be important to do so? If so, what would happen? It fails to import the whole thing?

**Comment by CreativeTechGuy** [comment]
Ah you are totally right, not a normal thing. I guess I'm just weird since I almost always edit via JSON since it's easier to copy existing configurations.

> It fails to import the whole thing?

Yeah just cancel the import and show the error.
