### ISSUE TITLE
Allow alert grouping

### ISSUE THREAD

**Issue by donkeywait** [adamk33n3r/runelite-watchdog#58]
Include group options like group alert debounce, grouped infobox alert, and group import/export as examples. Grouping would be convenient not only for toggling contextual alerts off and on, but also for certain situations where alerts could frequently overlap. 
Examples could include having a set of combat related alerts sharing an infobox, or multiple triggers for a single alert type. (eg sound of a trap springing or notification of trap item on ground sharing a debounce timer)
This would add another layer of flexibility to the plugin and already adds a lot more "logic" the user can utilize to craft more explicit and powerful alerts.

**Comment by adamk33n3r** [comment]
You can test this out here! https://github.com/adamk33n3r/runelite-watchdog/releases/tag/v3.0.0-alpha%2B2334

**Comment by adamk33n3r** [comment]
Closing this as it is in [feat/alert-hub](https://github.com/adamk33n3r/runelite-watchdog/tree/feat/alert-hub)
