### ISSUE TITLE
Custom sound glitch?

### ISSUE THREAD

**Issue by Tech-Freddie** [adamk33n3r/runelite-watchdog#6]
not sure if its a glitch but trying to set up a custom sound and it just plays the native alert sound it maybe just me not sure 

![sound](https://user-images.githubusercontent.com/62779882/201523562-edb3b98f-d5e0-452e-b232-4a9bd1588843.png)

**Comment by adamk33n3r** [comment]
I just looked into this, and it seems to be working for me. Can you check the logs? If there is an issue playing the audio file, then it will fall back to playing the native beep. I'm guessing there is an error in your runelite logs.

**Comment by Tech-Freddie** [comment]
checked the log didn't find anything like that instead came across these 

2022-11-13 07:25:40 [ForkJoinPool.commonPool-worker-19] ERROR c.a.r.watchdog.notifications.Sound - null
2022-11-13 07:25:41 [ForkJoinPool.commonPool-worker-19] ERROR c.a.r.watchdog.notifications.Sound - null
2022-11-13 07:36:03 [ForkJoinPool.commonPool-worker-19] WARN  c.a.r.watchdog.notifications.Sound - Unable to load sound

**Comment by Tech-Freddie** [comment]
turns out its the file i got , it will play on windows media player but not with runelite but other sound files will

**Comment by adamk33n3r** [comment]
Oh you'd probably have to change the log level to debug to see the one I mentioned, oops. After the `Unable to load sound` is there an additional exception?

**Comment by adamk33n3r** [comment]
> turns out its the file i got , it will play on windows media player but not with runelite but other sound files will

Oh ok, ya my guess is that maybe it's not actually a `wav` file. Or something other to do with the format. There's a quite limited capability with audio loading in base java.

**Comment by Tech-Freddie** [comment]
not sure downloaded the "wav" file from soundbible was trying to get it to make a sound when hespori entangles you maybe they have some weird encoding or something

**Comment by Tech-Freddie** [comment]
downloaded it as an mp3 and converted the file via an online converted and that seemed to do the trick so i got the sound i wanted

**Comment by adamk33n3r** [comment]
Cool! Glad it worked out for you! I'll update some information to be clearer about the restrictions.
