### ISSUE TITLE
[Feature] Duplicate

### ISSUE THREAD

**Issue by Classiick** [adamk33n3r/runelite-watchdog#67]
Would love to have a way to duplicate notifications so that it is quicker and easier to set up new notifications with similar notification modules. Maybe add a duplicate button like this?

![Untitled-1fdsdfsdfds](https://github.com/adamk33n3r/runelite-watchdog/assets/25242011/a2e0b130-4088-4088-bf1a-99a50b05882e)

**Comment by adamk33n3r** [comment]
![copy_icon](https://github.com/adamk33n3r/runelite-watchdog/assets/1350444/ae6065c1-b6cd-4590-8b18-8c329de2765e)
