### ISSUE TITLE
Feature Request: Audio triggers

### ISSUE THREAD

**Issue by salverrs** [adamk33n3r/runelite-watchdog#8]
Hi! Thanks so much for making this plugin, it's extremely versatile and useful in so many scenarios.

Just one suggestion for improvement: **Audio triggers**

I would love to be able to create custom alerts based on sound effects/area sounds being played. There are often times I need to play with very low volume or even muted, which can be a bit frustrating during tasks where sound cues are quite important. 

I believe the Runelite events relating to sounds are **SoundEffectPlayed** and **AreaSoundEffectPlayed**. If this is a feature you're interested in adding but don't have the time, I'm also happy to work on the feature myself and submit a PR here.

**Comment by adamk33n3r** [comment]
Oh that's an interesting idea! The biggest concern I have is how would you choose which sound to trigger on? We basically just have the sound ID to look at.

https://static.runelite.net/api/runelite-api/net/runelite/api/events/SoundEffectPlayed.html
https://static.runelite.net/api/runelite-api/net/runelite/api/events/AreaSoundEffectPlayed.html

**Comment by salverrs** [comment]
Most sound IDs can be found [on the wiki](https://oldschool.runescape.wiki/w/List_of_in-game_sound_IDs). There is also a plugin called [Visual Sounds](https://runelite.net/plugin-hub/show/visual-sounds) which displays the IDs of sounds currently being played.

For example, here's a mock alert for ruby bolts (e) procs:

![New Project(12)](https://user-images.githubusercontent.com/109300410/204820266-8b8edab9-17e4-4a93-8e68-7a7e3d231b10.png)

**Comment by adamk33n3r** [comment]
Oh nice, thanks for the info! We might even be able to link to that wiki page from the plugin. If not, at least mention it. Is there a difference between area sounds and normal sounds with regards to ids? In other words, would we have to have 2 separate alert types or some sort of switch? Or could we just have one "sound effect trigger" that would handle both? Do the ids overlap or are they shared?

Also, nice mock! Did you make that in code? I'm currently working on #7 right now and it's touching almost everything so I'll plan on adding this to that release.

**Comment by salverrs** [comment]
I did a bit of testing and the IDs do not overlap. Both sound effects and area sounds have unique IDs, so we can just use one alert type to cover both. I also discovered that if sound effects/area sounds are fully muted in the client, then the SoundEffectPlayed/AreaSoundEffectPlayed events do not fire, this is a shame but I still believe it's worth adding as most use cases won't be for fully muted clients.

Thanks, it was just a quick photoshop unfortunately haha. Awesome! Let me know if any issues come up.

**Comment by adamk33n3r** [comment]
Oh ok it just looked so good that I thought it had to have been done in code haha. Interesting note about the mute, another thing we can indicate on the alert.

**Comment by adamk33n3r** [comment]
@salverrs while we're at it, any other features you can think of worthy of v2? :)

**Comment by salverrs** [comment]
Hmm, how about a new notification type where it sets the local player's overhead text? I think the call would be `client.getLocalPlayer().setOverheadText(notification)`. I'm not sure how useful this would be for most users, but I could definitely see myself using it a lot haha.

**Comment by salverrs** [comment]
You might have seen my message from the other issue but I think there is a bug involving text formatting.

Coloured messages use tags to format text e.g. `<col=ef1020>Example message</col>`, and [ChatMessage.getMessage()](https://static.runelite.net/api/runelite-api/net/runelite/api/events/ChatMessage.html#getMessage()) does not remove these tags automatically.

Inside the OnChatMessage event handler, I think you need to parse the chat message first with [Text.removeFormattingTags()](https://static.runelite.net/api/runelite-client/net/runelite/client/util/Text.html#removeFormattingTags(java.lang.String)) to remove any tags, otherwise chat message triggers do not correctly detect messages.

 I didn't notice this until now because I've been using wildcards at the start and end of all my triggers because I'm lazy.

**Comment by adamk33n3r** [comment]
> Hmm, how about a new notification type where it sets the local player's overhead text? I think the call would be `client.getLocalPlayer().setOverheadText(notification)`. I'm not sure how useful this would be for most users, but I could definitely see myself using it a lot haha.

Oh wow I didn't even know you could set text like that! That'd be neat!
