### ISSUE TITLE
[Feature] Custom Image Alerts

### ISSUE THREAD

**Issue by SoggyBurritoVR** [adamk33n3r/runelite-watchdog#81]
Add an option to assign a **PNG** image to the **Overlay Notification**.

Would add the ability for users to create and use their own custom image as overlay alerts.

**Comment by adamk33n3r** [comment]
![image](https://github.com/adamk33n3r/runelite-watchdog/assets/1350444/9520b614-4f8e-408a-900a-5b72009fa0a5)
