### ISSUE TITLE
[Feature] Area alerts

### ISSUE THREAD

**Issue by MrPryor** [adamk33n3r/runelite-watchdog#82]
Option to trigger a alert when player reaches a area. (Tile and/or Tile distance around a set tile)

**Comment by adamk33n3r** [comment]
This plugin is more geared toward notifying while afk, so I'm not sure of the use case for notifying you when you reach a tile. Is this if you like click a path far away like in a maze or something and you want to be notified when you reach the destination? I'm thinking like in Taverly dungeon.

**Comment by adamk33n3r** [comment]
Thinking about this some more, how would you "select" a tile?

**Comment by MrPryor** [comment]
Shift + Right-Click just like tile markers.

**Comment by adamk33n3r** [comment]
so it would create a new alert from shift right clicking? how would you edit an existing alert's tile? wonder if instead in the alert panel you can click like "pick tile" button and then you just left click on a tile to select it.

**Comment by MrPryor** [comment]
Yah that would work, Radius Markers kinda works that way but just were you are standing.
