### ISSUE TITLE
Add a metronome?

### ISSUE THREAD

**Issue by isaacsanders** [adamk33n3r/runelite-watchdog#83]
I love the idea of notifying myself in different ways, and I like using the metronome in NMZ to know when to flick prayers. How would you feel about adding a metronome "alert" type so I can configure it more than I can the included metronome plugin?

**Comment by adamk33n3r** [comment]
I'd accept an Interval alert. Might be wonky syncing them up i.e. when does the interval start? But an "every X ms" alert doesn't seem too bad.
