### ISSUE TITLE
[Feature] Enable notification only when AFK

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#90]
Similar to the existing "only fire notification while the game is in the background" setting, it'd be super useful if you could conditionally enable a notification if you've been AFK for X seconds. The measurement of "AFK" would be: `Math.min(client.getKeyboardIdleTicks(), client.getMouseIdleTicks())`.

The use-case would be similar to the "only fire in background", some notifications are only needed to alert you when you aren't already paying attention. For example, if you are in a boss fight, you may not want low prayer notifications since you probably already know, but yet if you are afking and stepped away from your computer, you definitely want to be notified that your prayer is about to run out. Yet in that case, the game may not be backgrounded, you are just AFK.

------

If this feature is accepted, here's my implementation proposal:

* Next to the current "fire in background" toggle would be a new button for this new feature
* When toggling, it'd expand the notification box to add a new row which contains an input box for you to enter a number 0-1500 seconds (0 to 25 minutes). So the toggle is a boolean/number hybrid, it's either off, or a number indicating the number of seconds you are idle before triggering. For simplicity, it can just always be a number where 0 indicates off.

**Comment by CreativeTechGuy** [comment]
@adamk33n3r, do you like this idea? I'm happy to add it if you like the design.

**Comment by adamk33n3r** [comment]
Ya I think it's good. Have a whack at it. I can see it being a little complicated, touching a lot of different parts. So it'll be a good learning experience!

**Comment by CreativeTechGuy** [comment]
I may fail or it may not be how you would have wanted it to be done. But hopefully it'll help get us started and with a few tweaks it'll be good! 😄

**Comment by adamk33n3r** [comment]
Ya that's what PR reviews are for! 😂

**Comment by CreativeTechGuy** [comment]
Okay got it. PR is out. I think it looks really good. Just need some new icons. I wanted to ask you if you had a vision for that. Given the UX you've currently done I assume you have more graphic design skills than me. :)
