### ISSUE TITLE
[Feature] Chat Alerts

### ISSUE THREAD

**Issue by CreativeTechGuy** [adamk33n3r/runelite-watchdog#92]
Currently to get an alert based on player chat, we first need to use the Chat Notifications plugin to translate the chat message into a notification, and then use Watchdog to pick up that notification.

It'd be nice if Watchdog could setup notifications on player chat messages directly. This would have a few benefits:

* The Chat Notifications plugin makes the client taskbar icon blink since a notification was fired.
* The message is duplicated in chat (assuming the RuneLite Game message notifications setting is on)
* It requires setting up regex in a separate plugin which makes it hard to share the Watchdog alert since it requires external setup to work.

Use-case: The shooting star CC has a bot which announces the stars found in a predefined format `w###, t#, <location>`. I wanted to setup a notification for when a tier 6+ star was found. To do this currently, I first needed to setup the Chat Notifications plugin to highlight on regex `w[0-9]{3}, t[6-9]` and then set it to notify on highlight. Then from Watchdog, I could use the same regex to match the notification and then do the alert I wanted. It'd be great to remove those intermediary steps.

This seems like it'd be a pretty easy change as all of the wiring for this is currently setup in the plugin. Just currently the player chat messages are discarded, instead they'd be processed through this.

**Comment by adamk33n3r** [comment]
Ya originally the plan for the "game message" alert was to have all message types. The java class is even called `ChatAlert`. But I made the change before the first release of the plugin because I thought it would be too complicated and confusing. I'd be ok with adding that back in though. One thing though is that there are a lot of "message types"
![image](https://github.com/adamk33n3r/runelite-watchdog/assets/1350444/5584be2d-0b00-4518-969c-c512fd2f1f82)
So maybe we could abstract that to like "game message" vs "player message" instead of directly exposing the message type.

**Comment by CreativeTechGuy** [comment]
Will do! I'm working on the PR right now. I'm planning to refactor `ChatAlert` -> `GameMessageAlert` and then create a new `PlayerChatAlert`.

I was originally thinking that all of these player message types would be handled by a single player message alert class and would be differentiated by the user with regex. Are you thinking that it should have a more granular selection like the XP Drop alert where the user first has to select which message type they care about?

**Comment by adamk33n3r** [comment]
Changing class names is non-trivial so I wouldn't recommend doing that. But is there a reason we can't keep both game and player messages in a single alert type? Originally ya it was just going to be a dropdown select to choose which message type.

**Comment by adamk33n3r** [comment]
https://github.com/adamk33n3r/runelite-watchdog/commit/730165cdd6c7b9625b3e9922f1688d8c09681852#diff-adc71ce745fe878e5d1f5ae6c9875ee540c7b150e62093d6a4fccf95fbc3adc0

Here's the commit where I removed it

**Comment by adamk33n3r** [comment]
> Changing class names is non-trivial so I wouldn't recommend doing that. 

I wanted to clarify that this is in regards to json (de)serialization

**Comment by CreativeTechGuy** [comment]
> Changing class names is non-trivial so I wouldn't recommend doing that.

Yeah I see now that there's some fancy Java magic going on here. Okay I won't rename it.

I do think it'd be more clear though to have two different alert types (`Player Chat Message` and `Game Message`) in the list of alert types to make the distinction clearer. I remember this being a big point of confusion in the past.

**Comment by CreativeTechGuy** [comment]
I've published the PR so you can take a look at what I'm thinking. Let me know what you think! Seems to work great. Your code is very easy to extend! (Except the JSON magic which I avoided haha)

**Comment by adamk33n3r** [comment]
> I've published the PR so you can take a look at what I'm thinking. Let me know what you think! Seems to work great. Your code is very easy to extend! (Except the JSON magic which I avoided haha)

Are you referring the to the handle upgrade stuff in the alert manager? ya...it's something for sure hahaha

**Comment by CreativeTechGuy** [comment]
I am a JavaScript developer so the GSON magic is unfamiliar to me. But yeah it'd probably have to have made some converter since the types in the JSON are tied to the class name it seems.
