### ISSUE TITLE
How to create events or notifications

### ISSUE THREAD

**Issue by 2art** [adamk33n3r/runelite-watchdog#97]
I installed this plugin, but the configuration doesn't have anything recarding the actual events that should trigger notifications. This is what it looks like for me:

![Screenshot (16)](https://github.com/adamk33n3r/runelite-watchdog/assets/5929182/603b1146-879b-4feb-972f-a5fe8ea5c14c)

**Comment by 2art** [comment]
It only has configuration for the sound effects and stuff, nothing where I can configure the events that trigger the notifications

**Comment by iatethedinosaurs** [comment]
On the RuneLite sidebar, you want to click the little bell (2nd icon of the sidebar). There you can add alerts. 
![image](https://github.com/adamk33n3r/runelite-watchdog/assets/20849321/cdf109a0-8f5f-487e-8da0-f3c1573df7d8)
