### ISSUE TITLE
Hitpoints stat drain configuration does not work after taking damage

### ISSUE THREAD

**Issue by Winhert** [adamk33n3r/runelite-watchdog#98]
Not sure if this is working as intended but taking combat/poison damage will not trigger the alert
I've tested the whole alert with the button

**Comment by adamk33n3r** [comment]
Hmm, I'd have to test it out but I thought it worked before. I think I originally tested it with the rock you can eat to take damage. Can you export the alert and share it here?

**Comment by adamk33n3r** [comment]
I just tested it by taking damage and it worked for me. I did not test poison but I would think it would behave the same.
This is the alert that I tested with.
```json
[{"type":"StatChangedAlert","skill":"HITPOINTS","changedAmount":-1,"enabled":true,"name":"New Stat Changed Alert","debounceTime":0,"notifications":[{"type":"ScreenFlash","color":"#46FF0000","flashMode":"FLASH","flashDuration":2,"fireWhenFocused":true},{"type":"GameMessage","message":"Ouch, that hurts","fireWhenFocused":true}]}]
```
